/**
 * CSS Selectors for Rugs.fun Data Collection
 *
 * This file contains selectors for extracting game data from the rugs.fun website.
 * Selectors are automatically generated and updated by the Selector Discovery Assistant.
 *
 * Last Updated: 2024-01-15
 * Generated By: Selector Discovery Assistant v1.0
 */
export declare const selectors: {
    multiplier: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
    timer: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
    gameStatus: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
    playerCount: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
    totalWager: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
    roundId: {
        selector: string;
        fallback: string;
        description: string;
        type: string;
        stability: string;
    };
};
/**
 * Selector validation rules
 */
export declare const validationRules: {
    requiredSelectors: string[];
    optionalSelectors: string[];
    minSuccessRate: number;
    testDurationSeconds: number;
};
/**
 * Selector metadata
 */
export declare const metadata: {
    version: string;
    lastTested: string;
    testResults: {
        successRate: number;
        totalTests: number;
        successfulTests: number;
        lastTestDuration: number;
    };
    notes: string;
};
//# sourceMappingURL=selectors.d.ts.map