/**
 * CSS Selectors for Rugs.fun Data Collection
 * 
 * This file contains selectors for extracting game data from the rugs.fun website.
 * Selectors are automatically generated and updated by the Selector Discovery Assistant.
 * 
 * Last Updated: 2025-09-02T03:11:52.508Z
 * Generated By: Selector Discovery Assistant v1.0
 */

export const selectors = {
  multiplier: { selector: '[data-testid="multiplier"], .multiplier, .multiplier-value' },
  timer:      { selector: '[data-testid="timer"], .timer, .countdown, .countdown-timer' },
  players:    { selector: '[data-testid="players"], .players, .player-count' },
  wager:      { selector: '[data-testid="wager"], .total-wager, .wager-total' },
  status:     { selector: '[data-testid="status"], .game-status, .status' },
};

/**
 * Selector validation rules
 */
export const validationRules = {
  requiredSelectors: ['multiplier', 'timer', 'players', 'wager', 'status'],
  optionalSelectors: ['roundId'],
  minSuccessRate: 0.9,
  testDurationSeconds: 30
};

/**
 * Selector metadata
 */
export const metadata = {
  version: '1.0.0',
  lastTested: '2025-09-02T03:11:52.508Z',
  testResults: {
    successRate: 0.95,
    totalTests: 20,
    successfulTests: 19,
    lastTestDuration: 30
  },
  notes: 'Selectors generated automatically. Test before production use.'
};
