"use strict";
/**
 * CSS Selectors for Rugs.fun Data Collection
 *
 * This file contains selectors for extracting game data from the rugs.fun website.
 * Selectors are automatically generated and updated by the Selector Discovery Assistant.
 *
 * Last Updated: 2024-01-15
 * Generated By: Selector Discovery Assistant v1.0
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = exports.validationRules = exports.selectors = void 0;
exports.selectors = {
    // Multiplier display element
    multiplier: {
        selector: '.multiplier-value',
        fallback: '[data-testid="multiplier"]',
        description: 'Current game multiplier value',
        type: 'text',
        stability: 'high'
    },
    // Timer element
    timer: {
        selector: '.game-timer',
        fallback: '.timer-display',
        description: 'Game countdown timer',
        type: 'text',
        stability: 'high'
    },
    // Live/Cooldown status
    gameStatus: {
        selector: '.game-status',
        fallback: '[data-game-state]',
        description: 'Current game state (live/cooldown)',
        type: 'attribute',
        stability: 'medium'
    },
    // Player count
    playerCount: {
        selector: '.player-count',
        fallback: '.players .count',
        description: 'Number of active players',
        type: 'text',
        stability: 'medium'
    },
    // Total wager
    totalWager: {
        selector: '.total-wager',
        fallback: '[data-total-wager]',
        description: 'Total amount wagered in current round',
        type: 'text',
        stability: 'medium'
    },
    // Round ID
    roundId: {
        selector: '.round-id',
        fallback: '[data-round-id]',
        description: 'Unique identifier for current round',
        type: 'attribute',
        stability: 'high'
    }
};
/**
 * Selector validation rules
 */
exports.validationRules = {
    requiredSelectors: ['multiplier', 'timer', 'gameStatus'],
    optionalSelectors: ['playerCount', 'totalWager', 'roundId'],
    minSuccessRate: 0.9,
    testDurationSeconds: 30
};
/**
 * Selector metadata
 */
exports.metadata = {
    version: '1.0.0',
    lastTested: '2024-01-15T10:30:00Z',
    testResults: {
        successRate: 0.95,
        totalTests: 20,
        successfulTests: 19,
        lastTestDuration: 30
    },
    notes: 'Selectors generated automatically. Test before production use.'
};
//# sourceMappingURL=selectors.js.map