name: Lint and Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install
        
    - name: TypeScript build
      run: pnpm -w build
      
    - name: ESLint
      run: pnpm lint
      
    - name: Type check
      run: pnpm type-check
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        cd apps/analyzer
        pip install -r requirements.txt
        
    - name: Python lint (flake8)
      run: |
        cd apps/analyzer
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "No critical errors found"
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics || echo "Style warnings found"
        
    - name: Python type check (mypy)
      run: |
        cd apps/analyzer
        pip install mypy
        mypy . --ignore-missing-imports || echo "Type checking completed with warnings"
